In [1]:
import sys
sys.path.insert(1, '/home/ias627/tools')

In [2]:
from abg_python.snapshot_utils import openSnapshot
from abg_python.cosmo_utils import load_AHF
import numpy as np
import matplotlib.pyplot as plt
from numba import njit
from scripts import FIREtoVTK

In [3]:
exec(open('scripts/halo_analysis_scripts.py').read())

In [4]:
officialSimNames = {'h206':'A1',
                    'h29':'A2',
                    'h113':'A4',
                    'h2':'A8'}
simNameBase = '_HR_sn1dy300ro100ss'

# h2

In [5]:
simName = 'h2' + simNameBase

In [6]:
p1 = openSnapshot(f'/projects/b1026/anglesd/FIRE/{simName}', 277, 1, loud=1)

/projects/b1026/anglesd/FIRE/h2_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.0.hdf5
This is a cosmological snapshot... converting to physical units
/projects/b1026/anglesd/FIRE/h2_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.1.hdf5
/projects/b1026/anglesd/FIRE/h2_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.2.hdf5
/projects/b1026/anglesd/FIRE/h2_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.3.hdf5


In [11]:
posC, Rvir = load_AHF('', 277, p1['Redshift'], hubble=p1['HubbleParam'], ahf_path=f'/projects/b1026/halo_files/anglesd_m13/{simName}', extra_names_to_read=[])

In [26]:
posC, Rvir

(array([37042.33282303, 34138.53655707, 35864.77009903]), 358.6800568063578)

In [8]:
%time com, comlist, radiuslist = halo_center_wrapper(p1)

1 2997.113104248047 1.42347887e+08 [37116.453 34044.863 35870.312]
2 2922.1852766418456 1.42347886e+08 [37116.45  34044.867 35870.312]
3 2849.1306447257994 1.4234788e+08 [37116.45  34044.863 35870.305]
4 2777.902378607654 1.42347869e+08 [37116.457 34044.85  35870.33 ]
5 2708.454819142463 1.4234778e+08 [37116.414 34044.83  35870.348]
6 2640.7434486639013 1.42346773e+08 [37116.426 34044.855 35870.34 ]
7 2574.7248624473036 1.42342068e+08 [37116.23  34044.766 35870.195]
8 2510.356740886121 1.42329884e+08 [37116.1   34045.01  35870.164]
9 2447.5978223639677 1.42307105e+08 [37115.934 34045.367 35870.254]
10 2386.4078768048685 1.42257413e+08 [37115.484 34045.914 35869.95 ]
11 2326.7476798847465 1.42093763e+08 [37113.676 34047.754 35869.16 ]
12 2268.5789878876276 1.41824739e+08 [37110.76  34051.023 35868.195]
13 2211.864513190437 1.41437913e+08 [37107.05  34055.273 35866.65 ]
14 2156.567900360676 1.40946309e+08 [37102.066 34060.535 35864.953]
15 2102.653702851659 1.40335108e+08 [37096.777 3406

## Export shrinking sphere to VTK

In [23]:
for i, comi in enumerate(comlist):
    x, y, z = np.array([comi[0]]), np.array([comi[1]]), np.array([comi[2]])
    FIREtoVTK.Points1d(*comi, {'radius':np.array([radiuslist[i]])}, '/projects/b1026/isultan/h2_HR_sn1dy300ro100ss_277/shrinksphere/sphere'+str(i).zfill(3))

/projects/b1026/isultan/h2_HR_sn1dy300ro100ss_277/shrinksphere/sphere000.vtu
/projects/b1026/isultan/h2_HR_sn1dy300ro100ss_277/shrinksphere/sphere001.vtu
/projects/b1026/isultan/h2_HR_sn1dy300ro100ss_277/shrinksphere/sphere002.vtu
/projects/b1026/isultan/h2_HR_sn1dy300ro100ss_277/shrinksphere/sphere003.vtu
/projects/b1026/isultan/h2_HR_sn1dy300ro100ss_277/shrinksphere/sphere004.vtu
/projects/b1026/isultan/h2_HR_sn1dy300ro100ss_277/shrinksphere/sphere005.vtu
/projects/b1026/isultan/h2_HR_sn1dy300ro100ss_277/shrinksphere/sphere006.vtu
/projects/b1026/isultan/h2_HR_sn1dy300ro100ss_277/shrinksphere/sphere007.vtu
/projects/b1026/isultan/h2_HR_sn1dy300ro100ss_277/shrinksphere/sphere008.vtu
/projects/b1026/isultan/h2_HR_sn1dy300ro100ss_277/shrinksphere/sphere009.vtu
/projects/b1026/isultan/h2_HR_sn1dy300ro100ss_277/shrinksphere/sphere010.vtu
/projects/b1026/isultan/h2_HR_sn1dy300ro100ss_277/shrinksphere/sphere011.vtu
/projects/b1026/isultan/h2_HR_sn1dy300ro100ss_277/shrinksphere/sphere012.vtu

# all m13 tests

In [8]:
p1_277_all = { k:openSnapshot(f'/projects/b1026/anglesd/FIRE/{k+simNameBase}', 277, 1, loud=1) for k in officialSimNames.keys() }

/projects/b1026/anglesd/FIRE/h206_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.0.hdf5
This is a cosmological snapshot... converting to physical units
/projects/b1026/anglesd/FIRE/h206_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.1.hdf5
/projects/b1026/anglesd/FIRE/h206_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.2.hdf5
/projects/b1026/anglesd/FIRE/h206_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.3.hdf5
/projects/b1026/anglesd/FIRE/h29_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.0.hdf5
This is a cosmological snapshot... converting to physical units
/projects/b1026/anglesd/FIRE/h29_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.1.hdf5
/projects/b1026/anglesd/FIRE/h29_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.2.hdf5
/projects/b1026/anglesd/FIRE/h29_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.3.hdf5
/projects/b1026/anglesd/FIRE/h29_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.4.hdf5
/projects/b1026/anglesd/FIRE/h29_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.5.hdf5
/projects/b1026/anglesd/FIRE

In [11]:
AHF_277_all = { k:load_AHF('', 277, p1_277_all[k]['Redshift'], hubble=p1_277_all[k]['HubbleParam'], ahf_path=f'/projects/b1026/halo_files/anglesd_m13/{k+simNameBase}', extra_names_to_read=[]) for k in officialSimNames.keys() }

In [13]:
%time com, comlist, radiuslist = halo_center_wrapper(p1_277_all['h113'])

1 3448.2184204101563 6.4378959e+07 [35469.59  38182.19  39938.168]
2 3362.0129598999024 6.4378959e+07 [35469.59  38182.19  39938.168]
3 3277.9626359024046 6.4378959e+07 [35469.59  38182.19  39938.168]
4 3196.0135700048445 6.4378959e+07 [35469.59  38182.19  39938.168]
5 3116.113230754723 6.4378959e+07 [35469.59  38182.19  39938.168]
6 3038.210399985855 6.4378959e+07 [35469.59  38182.19  39938.168]
7 2962.2551399862086 6.4378958e+07 [35469.594 38182.2   39938.164]
8 2888.1987614865534 6.4378957e+07 [35469.582 38182.203 39938.156]
9 2815.9937924493893 6.4378956e+07 [35469.582 38182.203 39938.156]
10 2745.5939476381545 6.4378956e+07 [35469.582 38182.203 39938.156]
11 2676.9540989472007 6.4378956e+07 [35469.582 38182.203 39938.156]
12 2610.0302464735205 6.4378956e+07 [35469.582 38182.203 39938.156]
13 2544.7794903116824 6.4378955e+07 [35469.582 38182.203 39938.156]
14 2481.1600030538903 6.4378954e+07 [35469.582 38182.2   39938.156]
15 2419.1310029775427 6.4378953e+07 [35469.582 38182.2   39

In [14]:
com

array([35537.89 , 37944.426, 39883.215], dtype=float32)

# h113

In [24]:
simName = 'h113' + simNameBase
p1_h113 = openSnapshot(f'/projects/b1026/anglesd/FIRE/{simName}', 277, 1, loud=1)

/projects/b1026/anglesd/FIRE/h113_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.0.hdf5
This is a cosmological snapshot... converting to physical units
/projects/b1026/anglesd/FIRE/h113_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.1.hdf5
/projects/b1026/anglesd/FIRE/h113_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.2.hdf5
/projects/b1026/anglesd/FIRE/h113_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.3.hdf5


In [25]:
posC_h113, Rvir_h113 = load_AHF('', 277, p1_h113['Redshift'], hubble=p1_h113['HubbleParam'], ahf_path=f'/projects/b1026/halo_files/anglesd_m13/{simName}', extra_names_to_read=[])

In [26]:
%time com_h113, comlist_h113, radiuslist_h113 = halo_center_wrapper(p1_h113)

1 3448.2184204101563 6.4378959e+07 [35469.59  38182.19  39938.168]
2 3362.0129598999024 6.4378959e+07 [35469.59  38182.19  39938.168]
3 3277.9626359024046 6.4378959e+07 [35469.59  38182.19  39938.168]
4 3196.0135700048445 6.4378959e+07 [35469.59  38182.19  39938.168]
5 3116.113230754723 6.4378959e+07 [35469.59  38182.19  39938.168]
6 3038.210399985855 6.4378959e+07 [35469.59  38182.19  39938.168]
7 2962.2551399862086 6.4378958e+07 [35469.594 38182.2   39938.164]
8 2888.1987614865534 6.4378957e+07 [35469.582 38182.203 39938.156]
9 2815.9937924493893 6.4378956e+07 [35469.582 38182.203 39938.156]
10 2745.5939476381545 6.4378956e+07 [35469.582 38182.203 39938.156]
11 2676.9540989472007 6.4378956e+07 [35469.582 38182.203 39938.156]
12 2610.0302464735205 6.4378956e+07 [35469.582 38182.203 39938.156]
13 2544.7794903116824 6.4378955e+07 [35469.582 38182.203 39938.156]
14 2481.1600030538903 6.4378954e+07 [35469.582 38182.2   39938.156]
15 2419.1310029775427 6.4378953e+07 [35469.582 38182.2   39

In [27]:
com_h113

array([35537.89 , 37944.426, 39883.215], dtype=float32)

In [28]:
posC_h113

array([35537.95310827, 37944.45182004, 39883.45367158])

# h29

In [29]:
simName = 'h29' + simNameBase
p1_h29 = openSnapshot(f'/projects/b1026/anglesd/FIRE/{simName}', 277, 1, loud=1)

/projects/b1026/anglesd/FIRE/h29_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.0.hdf5
This is a cosmological snapshot... converting to physical units
/projects/b1026/anglesd/FIRE/h29_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.1.hdf5
/projects/b1026/anglesd/FIRE/h29_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.2.hdf5
/projects/b1026/anglesd/FIRE/h29_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.3.hdf5
/projects/b1026/anglesd/FIRE/h29_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.4.hdf5
/projects/b1026/anglesd/FIRE/h29_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.5.hdf5
/projects/b1026/anglesd/FIRE/h29_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.6.hdf5
/projects/b1026/anglesd/FIRE/h29_HR_sn1dy300ro100ss/snapdir_277/snapshot_277.7.hdf5


In [30]:
posC_h29, Rvir_h29 = load_AHF('', 277, p1_h29['Redshift'], hubble=p1_h29['HubbleParam'], ahf_path=f'/projects/b1026/halo_files/anglesd_m13/{simName}', extra_names_to_read=[])

In [33]:
%time com_h29, comlist_h29, radiuslist_h29 = halo_center_wrapper(p1_h29)

1 2866.6456787109373 1.13287393e+08 [35147.406 35939.324 37614.547]
2 2794.979536743164 1.13286464e+08 [35147.41  35939.445 37614.523]
3 2725.105048324585 1.1328551e+08 [35147.477 35939.34  37614.48 ]
4 2656.9774221164703 1.13282019e+08 [35147.6   35939.297 37614.58 ]
5 2590.5529865635585 1.13273969e+08 [35147.67  35939.27  37614.652]
6 2525.7891618994695 1.13260022e+08 [35147.836 35939.234 37614.74 ]
7 2462.644432851983 1.13211119e+08 [35148.35  35939.035 37614.723]
8 2401.078322030683 1.13067384e+08 [35148.598 35937.984 37613.656]
9 2341.051363979916 1.12770771e+08 [35148.188 35937.24  37610.246]
10 2282.525079880418 1.12324437e+08 [35151.15  35939.293 37606.69 ]
11 2225.461952883408 1.11981047e+08 [35152.902 35939.273 37603.965]
12 2169.8254040613224 1.11582306e+08 [35155.453 35940.797 37602.2  ]
13 2115.5797689597894 1.11047137e+08 [35159.305 35942.375 37600.453]
14 2062.6902747357944 1.10423289e+08 [35163.383 35943.51  37599.535]
15 2011.1230178673995 1.09448752e+08 [35167.652 359

In [34]:
com_h29

array([35380.145, 36058.246, 37643.027], dtype=float32)

In [32]:
posC_h29

array([35380.26066104, 36058.27797804, 37643.1734774 ])